version: "2"

services:
  database:
    image: dogstudio/mariadb
    ports:
      - "3306:3306"

  web:
    build: ../nginx-docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dev:/var/www/dev"
      - "./cut:/var/www/cut"
      - "./database:/var/www/database"

  php:
    image: dogstudio/php:5.6-fpm
    ports:
      - "9000:9000"
    volumes:
      - "./dev:/var/www/dev"