version: "2"

services:
  database:
    image: dogstudio/mariadb
    ports:
      - "3306:3306"
    volumes:  
      - "./database:/docker-entrypoint-initdb.d"

  php:
    image: dogstudio/php:7-fpm
    ports:
      - "9000:9000"
    volumes:
      - "./dev:/var/www/dev"
      - "./cut:/var/www/cut"
      - "./database:/var/www/database"

  web:
    image: dogstudio/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dev:/var/www/dev"
      - "./cut:/var/www/cut"
      - "./database:/var/www/database"
