version: "2"

services:
  database:
    image: dogstudio/mariadb
    ports:
      - "3306:3306"

  php:
    image: dogstudio/php:7-fpm
    ports:
      - "9000:9000"
    volumes:
      - "./dev:/var/www/dev"

  web:
    #image: dogstudio/nginx
    build: docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dev:/var/www/dev"
      - "./cut:/var/www/cut"
      - "./database:/var/www/database"
